version: '3.8'

services:
  artisan:
    build: .
    volumes:
      - .:/app
    links:
      - rabbitmq
    working_dir: /app
    user: 1000:1000
    entrypoint: php artisan

  default_consumer:
    build: .
    deploy:
      replicas: 2
    volumes:
      - .:/app
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    working_dir: /app
    user: 1000:1000
    command: php artisan default:consumer

  topic_consumer:
    build: .
    deploy:
      replicas: 2
    volumes:
      - .:/app
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    working_dir: /app
    user: 1000:1000
    command: php artisan topic:consumer

  header_consumer:
    build: .
    deploy:
      replicas: 2
    volumes:
      - .:/app
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    working_dir: /app
    user: 1000:1000
    command: php artisan header:consumer

  direct_consumer:
    build: .
    deploy:
      replicas: 2
    volumes:
      - .:/app
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    working_dir: /app
    user: 1000:1000
    command: php artisan direct:consumer

  rabbitmq:
    image: bitnami/rabbitmq:3.7
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volume:/bitnami
    environment:
      RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT: 1M
